# Generated by Django 5.2.7 on 2025-12-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
