# Generated by Django 5.2.7 on 2026-03-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OTP",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="phone_number",
        ),
    ]
