# Generated by Django 5.2.7 on 2026-04-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_myuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
